### ISSUE TITLE
AddPageNumberStamp package issues

### ISSUE THREAD

**Issue by nhojpatrick** [asposepdf/Aspose_Pdf_Java#12]
Same type of issue to https://github.com/asposeslides/Aspose_Slides_Java/issues/7

Any reason why you picked camel case names for package names.

Just wondering as both Sun and now Oracle recommend package names are all lower case, so avoid potential conflict with classes and interfaces.

https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

AddPageNumberStamp has the following package name;
package programmersguide.workingwithasposepdf.workingwithstampsandwatermarks.addpagenumberstamp.java;

But should be;
package com.aspose.pdf.examples.asposepdf.stampsandwatermarks;

**Comment by saqib-razzaq-aspose** [comment]
Fixed, please pull/download again.
