### ISSUE TITLE
.gitignore update for Eclipse, IntelliJ and Mac

### ISSUE THREAD

**Issue by nhojpatrick** [asposepdf/Aspose_Pdf_Java#13]
If you add the following lines into .gitignore it aids people using Eclipse, IntelliJ or Mac. I've add # so you can see which they refer to. I guess this might be a change you want to do for all the aspose products.
# Eclipse
.classpath
.project
.settings/
test-output/
# Intellij
.idea/
*.iml
*.iws
# Mac
.DS_Store

**Comment by saqib-razzaq-aspose** [comment]
Thanks, I have updated the .gitignore for Aspose.Pdf. Will be done for other repositories as well.
